name: format

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.1.2
      - name: install
        run: npm clean-install
      - name: format
        run: npm run format
      - name: commit
        run: |
          if [[ $(git status -s) ]]; then
            git config user.name github-actions
            git config user.email 41898282+github-actions[bot]@users.noreply.github.com
            git add .
            git commit -m "Format code using prettier"
            git push;
          fi
